name: unity_labs
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  intl: ^0.19.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.0
  dio: ^5.1.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_secure_storage: ^9.2.2
  iconsax: ^0.0.8
  image_picker: ^1.0.0
  photo_view: ^0.15.0
  syncfusion_flutter_pdfviewer: ^27.1.52
  video_player: ^2.6.1
  third_party_login: ^1.0.14
  firebase_core: ^2.32.0
  group_button: ^5.3.0
  share_plus: ^10.0.3
  pdf: ^3.10.6
  image: ^4.1.3
  path_provider: ^2.1.1
  http: ^1.2.2
  circular_countdown_timer: ^0.2.3
  flutter_rating_bar: ^4.0.1
  youtube_player_flutter: ^9.1.1
  syncfusion_flutter_charts: ^27.1.58
  just_audio: ^0.9.42
  firebase_core_platform_interface: ^5.4.0
  sign_in_with_apple: ^5.0.0  # ✅ updated to latest compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/useful/
    - assets/images/harmful/
    - assets/congratulations.json
    - assets/result.json
    - assets/video/
    - assets/footer/
