// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdghj9XrCJYYHxAnMosZVwlVRp9I1w5BA',
    appId: '1:1045411341624:web:ea5a15422e36d28813cdcd',
    messagingSenderId: '1045411341624',
    projectId: 'unitaqua-3b6b7',
    authDomain: 'unitaqua-3b6b7.firebaseapp.com',
    storageBucket: 'unitaqua-3b6b7.firebasestorage.app',
    measurementId: 'G-ETWB1WSVBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDth9zcvbyk7vpkEQYy0-ARCaHHMm81-ho',
    appId: '1:1045411341624:android:272c34656411ab1c13cdcd',
    messagingSenderId: '1045411341624',
    projectId: 'unitaqua-3b6b7',
    storageBucket: 'unitaqua-3b6b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhRlUmV0r49zn4qeQUh7zpA5IsoWvydns',
    appId: '1:1045411341624:ios:bd53d55d64fe3fef13cdcd',
    messagingSenderId: '1045411341624',
    projectId: 'unitaqua-3b6b7',
    storageBucket: 'unitaqua-3b6b7.firebasestorage.app',
    iosBundleId: 'com.unitaqua.unityLabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhRlUmV0r49zn4qeQUh7zpA5IsoWvydns',
    appId: '1:1045411341624:ios:bd53d55d64fe3fef13cdcd',
    messagingSenderId: '1045411341624',
    projectId: 'unitaqua-3b6b7',
    storageBucket: 'unitaqua-3b6b7.firebasestorage.app',
    iosBundleId: 'com.unitaqua.unityLabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdghj9XrCJYYHxAnMosZVwlVRp9I1w5BA',
    appId: '1:1045411341624:web:e48b2083f3b3a1b813cdcd',
    messagingSenderId: '1045411341624',
    projectId: 'unitaqua-3b6b7',
    authDomain: 'unitaqua-3b6b7.firebaseapp.com',
    storageBucket: 'unitaqua-3b6b7.firebasestorage.app',
    measurementId: 'G-40T83MGMS2',
  );
}
